# If true, SwiftLint will not fail if no lintable files are found.
allow_zero_lintable_files: true
# If true, SwiftLint will treat all warnings as errors.
strict: false
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)
blanket_disable_command:
  severity: warning
  allowed_rules: ["file_header", "file_length", "file_name", "file_name_no_space", "single_test_class"]
  always_blanket_disable: []
block_based_kvo:
  severity: warning
class_delegate_protocol:
  severity: warning
closing_brace:
  severity: warning
closure_parameter_position:
  severity: warning
colon:
  severity: warning
  flexible_right_spacing: false
  apply_to_dictionaries: true
comma:
  severity: warning
comment_spacing:
  severity: warning
compiler_protocol_init:
  severity: warning
computed_accessors_order:
  severity: warning
  order: get_set
control_statement:
  severity: warning
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false
deployment_target:
  severity: warning
  iOSApplicationExtension_deployment_target: 7.0
  iOS_deployment_target: 7.0
  macOSApplicationExtension_deployment_target: 10.9
  macOS_deployment_target: 10.9
  tvOSApplicationExtension_deployment_target: 9.0
  tvOS_deployment_target: 9.0
  watchOSApplicationExtension_deployment_target: 1.0
  watchOS_deployment_target: 1.0
discouraged_direct_init:
  severity: warning
  types: ["Bundle", "Bundle.init", "Bundle.init.init", "NSError", "NSError.init", "NSError.init.init", "UIDevice", "UIDevice.init", "UIDevice.init.init"]
duplicate_conditions:
  severity: error
duplicate_enum_cases:
  severity: error
duplicate_imports:
  severity: warning
duplicated_key_in_dictionary_literal:
  severity: warning
dynamic_inline:
  severity: error
empty_enum_arguments:
  severity: warning
empty_parameters:
  severity: warning
empty_parentheses_with_trailing_closure:
  severity: warning
file_length:
  warning: 400
  error: 1000
  ignore_comment_only_lines: false
for_where:
  severity: warning
  allow_for_as_filter: false
force_cast:
  severity: error
force_try:
  severity: error
function_body_length:
  warning: 50
  error: 100
function_parameter_count:
  warning: 5
  error: 8
  ignores_default_parameters: true
generic_type_name:
  min_length:
    warning: 1
    error: 0
  max_length:
    warning: 20
    error: 1000
  excluded: []
  allowed_symbols: []
  unallowed_symbols_severity: error
  validates_start_with_lowercase: error
identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 60
  excluded: ["^^id$$"]
  allowed_symbols: []
  unallowed_symbols_severity: error
  validates_start_with_lowercase: error
implicit_getter:
  severity: warning
inclusive_language:
  severity: warning
invalid_swiftlint_command:
  severity: warning
is_disjoint:
  severity: warning
large_tuple:
  warning: 2
  error: 3
leading_whitespace:
  severity: warning
legacy_cggeometry_functions:
  severity: warning
legacy_constant:
  severity: warning
legacy_constructor:
  severity: warning
legacy_hashing:
  severity: warning
legacy_nsgeometry_functions:
  severity: warning
legacy_random:
  severity: warning
line_length:
  warning: 120
  error: 200
  ignores_urls: false
  ignores_function_declarations: false
  ignores_comments: false
  ignores_interpolated_strings: false
mark:
  severity: warning
multiple_closures_with_trailing_closure:
  severity: warning
nesting:
  type_level:
    warning: 1
  function_level:
    warning: 2
  check_nesting_in_closures_and_statements: true
  always_allow_one_type_in_functions: false
no_fallthrough_only:
  severity: warning
no_space_in_method_call:
  severity: warning
notification_center_detachment:
  severity: warning
ns_number_init_as_function_reference:
  severity: warning
nsobject_prefer_isequal:
  severity: warning
opening_brace:
  severity: warning
  allow_multiline_func: false
operator_whitespace:
  severity: warning
orphaned_doc_comment:
  severity: warning
private_over_fileprivate:
  severity: warning
  validate_extensions: false
private_unit_test:
  severity: warning
  test_parent_classes: ["QuickSpec", "XCTestCase"]
protocol_property_accessors_order:
  severity: warning
reduce_boolean:
  severity: warning
redundant_discardable_let:
  severity: warning
redundant_objc_attribute:
  severity: warning
redundant_optional_initialization:
  severity: warning
redundant_set_access_control:
  severity: warning
redundant_string_enum_value:
  severity: warning
redundant_void_return:
  severity: warning
return_arrow_whitespace:
  severity: warning
self_in_property_initialization:
  severity: warning
shorthand_operator:
  severity: error
statement_position:
  severity: warning
  statement_mode: default
superfluous_disable_command:
  severity: warning
switch_case_alignment:
  severity: warning
  indented_cases: false
syntactic_sugar:
  severity: warning
todo:
  severity: warning
trailing_comma:
  severity: warning
  mandatory_comma: true
trailing_newline:
  severity: warning
trailing_semicolon:
  severity: warning
trailing_whitespace:
  severity: warning
  ignores_empty_lines: false
  ignores_comments: true
type_body_length:
  warning: 250
  error: 350
type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 40
    error: 1000
  excluded: []
  allowed_symbols: []
  unallowed_symbols_severity: error
  validates_start_with_lowercase: error
  validate_protocols: true
unavailable_condition:
  severity: warning
unneeded_break_in_switch:
  severity: warning
unneeded_override:
  severity: warning
unneeded_synthesized_initializer:
  severity: warning
unused_closure_parameter:
  severity: warning
unused_control_flow_label:
  severity: warning
unused_enumerated:
  severity: warning
unused_optional_binding:
  severity: warning
  ignore_optional_try: false
unused_setter_value:
  severity: warning
valid_ibinspectable:
  severity: warning
vertical_parameter_alignment:
  severity: warning
vertical_whitespace:
  severity: warning
  max_empty_lines: 1
void_function_in_ternary:
  severity: warning
void_return:
  severity: warning
xctfail_message:
  severity: warning
